EmployeeManagement/ViewModels/InternalEmployeeDetailViewModel.cs
namespace EmployeeManagement.ViewModels
{
    public class InternalEmployeeDetailViewModel
    {
        public Guid Id { get; set; }

        public string FirstName { get; set; } = string.Empty;

        public string LastName { get; set; } = string.Empty;

        public string FullName
        {
            get { return $"{FirstName} {LastName}"; }
        }

        public int YearsInService { get; set; }

        public decimal SuggestedBonus { get; set; }

        public decimal Salary { get; set; }

        public bool MinimumRaiseGiven { get; set; }

        public int JobLevel { get; set; }
    }
}

EmployeeManagement/Controllers/InternalEmployeeController.cs
using AutoMapper;
using EmployeeManagement.Business;
using EmployeeManagement.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeManagement.Controllers
{
    public class InternalEmployeeController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IMapper _mapper;
        private readonly IPromotionService _promotionService;

        public InternalEmployeeController(IEmployeeService employeeService,
            IMapper mapper,
            IPromotionService promotionService)
        {
            _employeeService = employeeService;
            _mapper = mapper;
            _promotionService = promotionService;
        }

        [HttpGet]
        public IActionResult AddInternalEmployee()
        {
            return View(new CreateInternalEmployeeViewModel()); 
        }

        [HttpPost]
        public async Task<IActionResult> AddInternalEmployee(
            CreateInternalEmployeeViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            else
            {
                // create an internal employee entity with default values filled out
                // and the values the user inputted
                var internalEmplooyee =
                    await _employeeService.CreateInternalEmployeeAsync(
                        model.FirstName, model.LastName);

                // persist it
                await _employeeService.AddInternalEmployeeAsync(internalEmplooyee);
            }

            return RedirectToAction("Index", "EmployeeOverview");
        }

        [HttpGet]
        public async Task<IActionResult> InternalEmployeeDetails(
            [FromRoute(Name = "id")] Guid? employeeId)
        {
            if (!employeeId.HasValue)
            {
                if (Guid.TryParse(HttpContext?.Session?.GetString("EmployeeId"),
                      out Guid employeeIdFromSession))
                {
                    employeeId = employeeIdFromSession;
                }
                else if (Guid.TryParse(TempData["EmployeeId"]?.ToString(),
                     out Guid employeeIdFromTempData))
                {
                    employeeId = employeeIdFromTempData;
                }
                else
                {
                    return RedirectToAction("Index", "EmployeeOverview");
                }
            }

            var internalEmployee = await _employeeService
                .FetchInternalEmployeeAsync(employeeId.Value); 
            if (internalEmployee == null)
            {
                return RedirectToAction("Index", "EmployeeOverview"); 
            }
             
            return View(_mapper.Map<InternalEmployeeDetailViewModel>(
                internalEmployee));  
        }

        [HttpPost]
        public async Task<IActionResult> ExecutePromotionRequest(
            [FromForm(Name = "id")] Guid? employeeId)
        {
            if (!employeeId.HasValue)
            {
                return RedirectToAction("Index", "EmployeeOverview");
            }

            var internalEmployee = await _employeeService
                .FetchInternalEmployeeAsync(employeeId.Value);

            if (internalEmployee == null)
            {
                return RedirectToAction("Index", "EmployeeOverview");
            }

            if (await _promotionService.PromoteInternalEmployeeAsync(
                internalEmployee))
            {
                ViewBag.PromotionRequestMessage = "Employee was promoted.";

                // get the updated employee values
                internalEmployee = await _employeeService
                    .FetchInternalEmployeeAsync(employeeId.Value);
            }
            else
            {
                ViewBag.PromotionRequestMessage = 
                    "Sorry, this employee isn't eligible for promotion.";
            }

            return View("InternalEmployeeDetails", 
                _mapper.Map<InternalEmployeeDetailViewModel>(internalEmployee));
        }
    }
}

EmployeeManagement/Views/InternalEmployee/AddInternalEmployee.cshtml
@model EmployeeManagement.ViewModels.CreateInternalEmployeeViewModel 
@{
    ViewData["Title"] = "Add Internal Employee";
}

<h1 class="display-3">Add Internal Employee</h1>

    <form method="post" asp-controller="InternalEmployee" asp-action="AddInternalEmployee">
        <fieldset class="form-group">
            First name:
            <input type="text" class="form-control" id="firstName" name="FirstName" placeholder="First name" required />
        </fieldset>
        <fieldset class="form-group">
            Last name: 
            <input type="text" class="form-control" id="lastName" name="LastName" placeholder="Last name" required />
        </fieldset>
        <input type="submit" value="Add" id="btnAdd" name="btnAdd" class="btn btn-primary" />
    </form>

EmployeeManagement/Views/InternalEmployee/InternalEmployeeDetails.cshtml
@model EmployeeManagement.ViewModels.InternalEmployeeDetailViewModel 
@{
    ViewData["Title"] = "Internal Employee Details";
}
 
 <div class="row">
    <div class="col-md-4">Name:</div>
    <div class="col-md-4">@Model?.FullName</div>
</div>
<div class="row">
    <div class="col-md-4">Salary:</div>
    <div class="col-md-4">@Model?.Salary</div>
</div>
<div class="row">
    <div class="col-md-4">Years in service:</div>
    <div class="col-md-4">@Model?.YearsInService </div>
</div>
<div class="row">
    <div class="col-md-4">Suggested bonus:</div>
    <div class="col-md-4">@Model?.SuggestedBonus </div> 
</div>
<div class="row">
    <div class="col-md-4">Current job level:</div>
    <div class="col-md-4">@Model?.JobLevel </div> 
</div> 
<div>
    <form method="post" asp-controller="InternalEmployee" asp-action="ExecutePromotionRequest">
       <input type="hidden" asp-for="Id" /> 
       <input type="submit" 
            class="btn btn-primary"  
            value="Request promotion" />
    </form>
</div>
<div class="row"> 
    <div class="col-md-8 fw-bold">@ViewBag.PromotionRequestMessage</div>
</div> 