EmployeeManagement/Controllers/EmployeeOverviewController.cs
using AutoMapper;
using EmployeeManagement.Business;
using EmployeeManagement.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmployeeManagement.Controllers
{
    public class EmployeeOverviewController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IMapper _mapper;

        public EmployeeOverviewController(IEmployeeService employeeService, 
            IMapper mapper)
        {
            _employeeService = employeeService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var internalEmployees = await _employeeService
                .FetchInternalEmployeesAsync();

            // with manual mapping
            //var internalEmployeeForOverviewViewModels =
            //    internalEmployees.Select(e => 
            //        new InternalEmployeeForOverviewViewModel()
            //        {
            //            Id = e.Id,
            //            FirstName = e.FirstName,
            //            LastName = e.LastName,
            //            Salary = e.Salary,
            //            SuggestedBonus = e.SuggestedBonus,
            //            YearsInService = e.YearsInService
            //        });

            // with AutoMapper
            var internalEmployeeForOverviewViewModels =
                _mapper.Map<IEnumerable<InternalEmployeeForOverviewViewModel>>(internalEmployees);

            return View(
                new EmployeeOverviewViewModel(internalEmployeeForOverviewViewModels));
        }

        [Authorize]
        public IActionResult ProtectedIndex()
        {
            // depending on the role, return a different result

            if (User.IsInRole("Admin"))
            {
                return RedirectToAction("AdminIndex", "EmployeeManagement");
            }

            return RedirectToAction("Index", "EmployeeManagement");
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmployeeManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmployeeManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="EmployeeOverview" asp-action="Index">Employee Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmployeeOverview" asp-action="Index">Home</a>
                        </li>                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">      
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>